<a href="https://colab.research.google.com/github/addagarla-sairaju/ML-PYTHON/blob/main/assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###ASSIGNMENT
Q1. Perform arithmetic operations on NumPy arrays.

In [ ]:
import numpy as np
a=np.array([1, 2, 3])
b=np.array([4, 5, 6])
print("addition",a + b)
print("subtraction",a-b)
print("multiplication",a*b)
print("division",a/b)

addition [5 7 9]
subtraction [-3 -3 -3]
multiplication [ 4 10 18]
division [0.25 0.4  0.5 ]


###Q2 Write a script to compute the mean and standard deviation of a NumPy array.


# New Section

In [ ]:
arr=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
mean=np.mean(arr)
std_dev=np.std(arr)
print("mean:",mean,"std:",std_dev)

mean: 5.5 std: 2.8722813232690143


##Q3. Create a NumPy array of integers from 10 to 50 with a step size of 5.

In [ ]:

arr=np.arange(10, 51, 5)
print( "array:",arr)


array: [10 15 20 25 30 35 40 45 50]


###Q4. Reshape the array into a 2x4 matrix

In [ ]:
import numpy as np

arr=np.arange(10, 51, 5)[:8]
reshaped=arr.reshape(2, 4)

print("reshaped:",reshaped)


reshaped: [[10 15 20 25]
 [30 35 40 45]]


Q5.Given the array arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]):
• Extract the sub-matrix containing the last two rows and first two columns.
• Replace all elements greater than 4 with 0.

In [ ]:

arr=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
sub_matrix=arr[1:, :2]
arr[arr > 4] = 0
print("sub:",sub_matrix)
print("array",arr)


sub: [[4 0]
 [0 0]]
array [[1 2 3]
 [4 0 0]
 [0 0 0]]


Q6.. Create two 1D arrays:
* • a = np.array([1, 2, 3])
* • b = np.array([4, 5, 6])
* • Perform element-wise addition, multiplication, and division.

In [ ]:

a=np.array([1, 2, 3])
b=np.array([4, 5, 6])
addition=a + b
multiplication=a*b
division =a/b
addition,multiplication, division


(array([5, 7, 9]), array([ 4, 10, 18]), array([0.25, 0.4 , 0.5 ]))

Q7. Create a random NumPy array of size (4, 4). Compute:
• Mean of each column.
• Maximum value of the entire array.
• Sum of all elements.

In [ ]:
arr=np.random.randint(1, 100, size=(4, 4))
mean_column=np.mean(arr, axis=0)
max_value=np.max(arr)
sum_elements=np.sum(arr)

mean_column, max_value, sum_elements


582

Q8.Given the array arr = np.array([1, 2, 3, 4]), add 10 to each element and multiply
the result by 2.

In [ ]:

arr=np.array([1, 2, 3, 4])
result=(arr + 10) * 2
result


array([22, 24, 26, 28])

Q9.  Perform advanced slicing and indexing on a 3D array.
Create a 3D NumPy array arr of shape (3, 4, 5) with random integers ranging from
1 to 100. Perform the following:
• Extract the second "layer" (i.e., the second 2D array) in the first dimension.
• Extract the first two rows and the last three columns from each "layer."
• Replace all elements divisible by 3 with -1.

In [ ]:
import numpy as np
arr=np.random.randint(1, 100, size=(3, 4, 5))
second_layer=arr[1]
extracted_part=arr[:, :2, -3:]
arr[arr % 3==0] =-1
print("second layer:",second_layer)
print("extracted:",extracted_part)
print("array:",arr)


second layer: [[37 53 16 -1 52]
 [-1 89 -1 -1 95]
 [23 80 52 20 22]
 [26 80 -1 14 -1]]
extracted: [[[-1 26 28]
  [73  4 32]]

 [[16 -1 52]
  [-1 -1 95]]

 [[56 -1 80]
  [ 5 25 52]]]
array: [[[50 -1 -1 26 28]
  [62 -1 73  4 32]
  [-1 -1 -1 62 -1]
  [-1 25 82 50 70]]

 [[37 53 16 -1 52]
  [-1 89 -1 -1 95]
  [23 80 52 20 22]
  [26 80 -1 14 -1]]

 [[35 -1 56 -1 80]
  [89 95  5 25 52]
  [68  4 74 29 35]
  [-1 32 56  2 55]]]


Q10.Work with broadcasting and advanced operations in NumPy.
 Create a NumPy array arr of shape (3, 3) with random integers between
 1 and 20. Perform the following:
• Subtract the mean of each row from its respective elements (row-wise
normalization).
• Create a new array by squaring all the elements in arr.
• Find the indices of the top 3 maximum values in the entire array.

In [ ]:

arr=np.random.randint(1, 20, size=(3, 3))
row_mean=np.mean(arr, axis=1, keepdims=True)
normalized_arr=arr-row_mean
squared_arr=np.power(arr, 2)
top_3_indices=np.unravel_index(np.argsort(arr.ravel())[-3:], arr.shape)
print("normalized",normalized_arr)
print("square",squared_arr)
print("top 3 indices",top_3_indices)


normalized [[-5.66666667  3.33333333  2.33333333]
 [ 0.33333333 -7.66666667  7.33333333]
 [-4.66666667  1.33333333  3.33333333]]
square [[ 64 289 256]
 [121   9 324]
 [ 64 196 256]]
top 3 indices (array([2, 0, 1]), array([2, 1, 2]))
